import pytest
from Library.Database.Query import QueryAPI
from Library.Database.Database import DatabaseAPI
from Library.Database.Oracle import OracleDatabaseAPI
from Library.Database.Postgres import PostgresDatabaseAPI
from Library.Database.Microsoft import MicrosoftDatabaseAPI
_DRIVERS_ = (PostgresDatabaseAPI, MicrosoftDatabaseAPI, OracleDatabaseAPI)
def build(driver):
    return driver.__new__(driver)
def carry(driver, columns='"UID", "Ask"'):
    return build(driver)._carry_(schema="Market", table="Tick", columns=columns, source="source")
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_carry_copies_every_column(driver):
    statement = carry(driver)
    assert "INSERT INTO" in statement
    assert statement.count('"UID", "Ask"') == 2
    assert "source" in statement
def test_carry_base_is_a_plain_insert():
    statement = DatabaseAPI._carry_(build(PostgresDatabaseAPI), schema="Market", table="Tick", columns='"UID"', source="source")
    assert statement.startswith("INSERT INTO")
    assert "IDENTITY" not in statement.upper()
def test_carry_postgres_overrides_the_identity():
    assert "OVERRIDING SYSTEM VALUE" in carry(PostgresDatabaseAPI)
def test_carry_microsoft_brackets_the_insert():
    statement = carry(MicrosoftDatabaseAPI)
    assert statement.index("SET IDENTITY_INSERT [Market].[Tick] ON") < statement.index("INSERT INTO")
    assert statement.index("INSERT INTO") < statement.index("SET IDENTITY_INSERT [Market].[Tick] OFF")
    assert statement.count("TableHasIdentity") == 2
def test_carry_oracle_restores_the_identity():
    statement = carry(OracleDatabaseAPI)
    assert statement.index("GENERATED BY DEFAULT AS IDENTITY") < statement.index("EXECUTE IMMEDIATE 'INSERT INTO")
    assert statement.index("EXECUTE IMMEDIATE 'INSERT INTO") < statement.index("GENERATED ALWAYS AS IDENTITY")
    assert statement.count("generated IS NOT NULL") == 2
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_carry_holds_no_parameter_tokens(driver):
    statement = carry(driver)
    assert QueryAPI(statement)(driver._PARAMETER_TOKEN_)[0] == statement
def ordered(driver, columns):
    instance = build(driver)
    instance._STRUCTURE_ = {"UID": int, "Ask": float, "Bid": float}
    instance._ordinals_ = lambda **kwargs: columns
    return instance
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_disordered_accepts_the_declared_order(driver):
    assert ordered(driver, ["UID", "Ask", "Bid"]).disordered(schema="Market", table="Tick") is False
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_disordered_rejects_a_drifted_order(driver):
    assert ordered(driver, ["UID", "Bid", "Ask"]).disordered(schema="Market", table="Tick") is True
def test_disordered_ignores_an_unknown_table():
    assert ordered(PostgresDatabaseAPI, []).disordered(schema="Market", table="Tick") is False
def test_disordered_needs_a_table():
    assert ordered(PostgresDatabaseAPI, ["UID"]).disordered(schema="Market", table=None) is False
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_realign_declines_without_a_source(driver):
    instance = build(driver)
    assert instance.realign(schema="Market", table="Tick", source=None) is instance
    assert instance.realign(schema="Market", table=None, source="Tick_a1b2c3d4") is instance
@pytest.mark.parametrize("driver", _DRIVERS_)
def test_realign_reads_a_catalog(driver):
    assert driver.realign is not DatabaseAPI.realign or driver is DatabaseAPI
def test_ordinals_reads_the_standard_catalog():
    assert MicrosoftDatabaseAPI._ordinals_ is DatabaseAPI._ordinals_
    assert PostgresDatabaseAPI._ordinals_ is DatabaseAPI._ordinals_
    assert OracleDatabaseAPI._ordinals_ is not DatabaseAPI._ordinals_
_SCHEMA_ = "MigrateProbe"
@pytest.fixture
def probe():
    from Library.Database.Postgres import PostgresDatabaseAPI as Driver
    from Library.Database.Database import PrimaryKey, ForeignKey
    from Library.Database.Dataframe import pl
    from Library.Database.Query import QueryAPI as Q
    with Driver(database="Tests") as db:
        try: db.delete(schema=_SCHEMA_)
        except Exception: pass
        db.create(schema=_SCHEMA_)
        db.create(schema=_SCHEMA_, table="Parent", structure={"UID": PrimaryKey(pl.Int64)})
        drifted = {"UID": PrimaryKey(pl.Int64), "Value": pl.Float64,
                   "Parent": ForeignKey(pl.Int64, reference=f'"{_SCHEMA_}"."Parent"("UID")')}
        db.create(schema=_SCHEMA_, table="Child", structure=drifted)
        db.executeone(Q(f'INSERT INTO "{_SCHEMA_}"."Parent" ("UID") VALUES (1)'), admin=False)
        db.executeone(Q(f'INSERT INTO "{_SCHEMA_}"."Child" ("UID", "Value", "Parent") VALUES (1, 2.5, 1)'), admin=False)
        yield db
        try: db.delete(schema=_SCHEMA_)
        except Exception: pass
def tables(db):
    from Library.Database.Query import QueryAPI as Q
    rows = db.executeone(Q(f"SELECT table_name FROM information_schema.tables WHERE table_schema = '{_SCHEMA_}'"), admin=False).fetchall(legacy=False)
    return sorted(row["table_name"] for row in db._records_(rows))
def test_discard_refuses_a_table_something_depends_on(probe):
    with pytest.raises(Exception): probe.discard(schema=_SCHEMA_, table="Parent")
    assert "Parent" in tables(probe)
def test_discard_drops_a_table_nothing_depends_on(probe):
    probe.discard(schema=_SCHEMA_, table="Child")
    assert "Child" not in tables(probe)
def test_a_failed_rebuild_restores_the_original(probe):
    from Library.Database.Database import PrimaryKey, ForeignKey
    from Library.Database.Dataframe import pl
    from Library.Database.Query import QueryAPI as Q
    before = probe._ordinals_(schema=_SCHEMA_, table="Child")
    declared = {"UID": PrimaryKey(pl.Int64), "Parent": ForeignKey(pl.Int64, reference=f'"{_SCHEMA_}"."Parent"("UID")'), "Value": pl.Float64}
    probe._carry_ = lambda **kwargs: f'INSERT INTO "{_SCHEMA_}"."Child" ("UID") SELECT "NoSuchColumn" FROM "{_SCHEMA_}"."Parent"'
    with pytest.raises(Exception): probe.migrate(schema=_SCHEMA_, table="Child", structure=declared)
    del probe._carry_
    assert tables(probe) == ["Child", "Parent"]
    assert probe._ordinals_(schema=_SCHEMA_, table="Child") == before
    rows = probe.executeone(Q(f'SELECT "UID", "Value", "Parent" FROM "{_SCHEMA_}"."Child"'), admin=False).fetchall(legacy=False)
    assert probe._records_(rows) == [{"UID": 1, "Value": 2.5, "Parent": 1}]
def test_a_failed_rebuild_keeps_the_foreign_key(probe):
    from Library.Database.Database import PrimaryKey, ForeignKey
    from Library.Database.Dataframe import pl
    from Library.Database.Query import QueryAPI as Q
    declared = {"UID": PrimaryKey(pl.Int64), "Parent": ForeignKey(pl.Int64, reference=f'"{_SCHEMA_}"."Parent"("UID")'), "Value": pl.Float64}
    probe._carry_ = lambda **kwargs: "SELECT does_not_exist_xyz()"
    with pytest.raises(Exception): probe.migrate(schema=_SCHEMA_, table="Child", structure=declared)
    del probe._carry_
    rows = probe.executeone(Q(f"""SELECT conname FROM pg_constraint
                                  WHERE contype = 'f' AND conrelid = '"{_SCHEMA_}"."Child"'::regclass"""), admin=False).fetchall(legacy=False)
    assert probe._records_(rows), "the foreign key did not survive the failed rebuild"