namespace cAlgo.Robots
{
    public enum StrategyType
    {
        Download = 1,
        NNFX = 2,
        DDPG = 3,
    }

    public enum VerboseLevel
    {
        Silent = 0,
        Exception = 1,
        Error = 2,
        Warning = 3,
        Alert = 4,
        Info = 5,
        Debug = 6,
    }

    public enum SystemMode
    {
        Live = 1,
        Simulation = 2,
        Testing = 3,
        Backtesting = 4,
        Optimization = 5,
        Learning = 6,
    }

    public enum UpdateID
    {
        Complete = 0,
        Account = 1,
        Security = 2,
        OpenedBuyPosition = 3,
        OpenedSellPosition = 4,
        ModifiedBuyPositionVolume = 5,
        ModifiedBuyPositionStopLoss = 6,
        ModifiedBuyPositionTakeProfit = 7,
        ModifiedSellPositionVolume = 8,
        ModifiedSellPositionStopLoss = 9,
        ModifiedSellPositionTakeProfit = 10,
        ClosedBuyPosition = 11,
        ClosedSellPosition = 12,
        Tick = 13,
        BarOpened = 14,
        BarClosed = 15,
        AskAboveTarget = 16,
        AskBelowTarget = 17,
        BidAboveTarget = 18,
        BidBelowTarget = 19,
        Shutdown = 20,
        OpenedBuyStopOrder = 21,
        OpenedSellStopOrder = 22,
        ModifiedBuyStopOrderVolume = 23,
        ModifiedBuyStopOrderStopPrice = 24,
        ModifiedBuyStopOrderStopLoss = 25,
        ModifiedBuyStopOrderTakeProfit = 26,
        ModifiedSellStopOrderVolume = 27,
        ModifiedSellStopOrderStopPrice = 28,
        ModifiedSellStopOrderStopLoss = 29,
        ModifiedSellStopOrderTakeProfit = 30,
        ClosedBuyStopOrder = 31,
        ClosedSellStopOrder = 32,
        FilledBuyStopOrder = 33,
        FilledSellStopOrder = 34,
        ExpiredBuyStopOrder = 35,
        ExpiredSellStopOrder = 36,
        OpenedBuyLimitOrder = 37,
        OpenedSellLimitOrder = 38,
        ModifiedBuyLimitOrderVolume = 39,
        ModifiedBuyLimitOrderLimitPrice = 40,
        ModifiedBuyLimitOrderStopLoss = 41,
        ModifiedBuyLimitOrderTakeProfit = 42,
        ModifiedSellLimitOrderVolume = 43,
        ModifiedSellLimitOrderLimitPrice = 44,
        ModifiedSellLimitOrderStopLoss = 45,
        ModifiedSellLimitOrderTakeProfit = 46,
        ClosedBuyLimitOrder = 47,
        ClosedSellLimitOrder = 48,
        FilledBuyLimitOrder = 49,
        FilledSellLimitOrder = 50,
        ExpiredBuyLimitOrder = 51,
        ExpiredSellLimitOrder = 52,
        OpenedBuyStopLimitOrder = 53,
        OpenedSellStopLimitOrder = 54,
        ModifiedBuyStopLimitOrderVolume = 55,
        ModifiedBuyStopLimitOrderStopPrice = 56,
        ModifiedBuyStopLimitOrderLimitPrice = 57,
        ModifiedBuyStopLimitOrderStopLoss = 58,
        ModifiedBuyStopLimitOrderTakeProfit = 59,
        ModifiedSellStopLimitOrderVolume = 60,
        ModifiedSellStopLimitOrderStopPrice = 61,
        ModifiedSellStopLimitOrderLimitPrice = 62,
        ModifiedSellStopLimitOrderStopLoss = 63,
        ModifiedSellStopLimitOrderTakeProfit = 64,
        ClosedBuyStopLimitOrder = 65,
        ClosedSellStopLimitOrder = 66,
        FilledBuyStopLimitOrder = 67,
        FilledSellStopLimitOrder = 68,
        ExpiredBuyStopLimitOrder = 69,
        ExpiredSellStopLimitOrder = 70,
        StopLossBuyPosition = 71,
        StopLossSellPosition = 72,
        TakeProfitBuyPosition = 73,
        TakeProfitSellPosition = 74,
        MarginCallBuyPosition = 75,
        MarginCallSellPosition = 76,
        Denied = 77,
        Exception = 78,
    }

    public enum ActionID
    {
        Complete = 0,
        OpenBuyPosition = 1,
        OpenSellPosition = 2,
        ModifyBuyPositionVolume = 3,
        ModifyBuyPositionStopLoss = 4,
        ModifyBuyPositionTakeProfit = 5,
        ModifySellPositionVolume = 6,
        ModifySellPositionStopLoss = 7,
        ModifySellPositionTakeProfit = 8,
        CloseBuyPosition = 9,
        CloseSellPosition = 10,
        AskAboveTarget = 11,
        AskBelowTarget = 12,
        BidAboveTarget = 13,
        BidBelowTarget = 14,
        OpenBuyStopOrder = 15,
        OpenSellStopOrder = 16,
        ModifyBuyStopOrderVolume = 17,
        ModifyBuyStopOrderStopPrice = 18,
        ModifyBuyStopOrderStopLoss = 19,
        ModifyBuyStopOrderTakeProfit = 20,
        ModifySellStopOrderVolume = 21,
        ModifySellStopOrderStopPrice = 22,
        ModifySellStopOrderStopLoss = 23,
        ModifySellStopOrderTakeProfit = 24,
        CloseBuyStopOrder = 25,
        CloseSellStopOrder = 26,
        OpenBuyLimitOrder = 27,
        OpenSellLimitOrder = 28,
        ModifyBuyLimitOrderVolume = 29,
        ModifyBuyLimitOrderLimitPrice = 30,
        ModifyBuyLimitOrderStopLoss = 31,
        ModifyBuyLimitOrderTakeProfit = 32,
        ModifySellLimitOrderVolume = 33,
        ModifySellLimitOrderLimitPrice = 34,
        ModifySellLimitOrderStopLoss = 35,
        ModifySellLimitOrderTakeProfit = 36,
        CloseBuyLimitOrder = 37,
        CloseSellLimitOrder = 38,
        OpenBuyStopLimitOrder = 39,
        OpenSellStopLimitOrder = 40,
        ModifyBuyStopLimitOrderVolume = 41,
        ModifyBuyStopLimitOrderStopPrice = 42,
        ModifyBuyStopLimitOrderLimitPrice = 43,
        ModifyBuyStopLimitOrderStopLoss = 44,
        ModifyBuyStopLimitOrderTakeProfit = 45,
        ModifySellStopLimitOrderVolume = 46,
        ModifySellStopLimitOrderStopPrice = 47,
        ModifySellStopLimitOrderLimitPrice = 48,
        ModifySellStopLimitOrderStopLoss = 49,
        ModifySellStopLimitOrderTakeProfit = 50,
        CloseBuyStopLimitOrder = 51,
        CloseSellStopLimitOrder = 52,
    }
}