namespace cAlgo.Robots
{
    public enum PositionTypeID
    {
        Normal = 0,
        Continuation = 1,
    }

    public enum StrategyType
    {
        Download = 1,
        NNFX = 2,
        DDPG = 3,
    }

    public enum VerboseLevel
    {
        Silent = 0,
        Exception = 1,
        Error = 2,
        Warning = 3,
        Alert = 4,
        Info = 5,
        Debug = 6,
    }

    public enum SystemMode
    {
        Live = 1,
        Simulation = 2,
        Testing = 3,
        Backtesting = 4,
        Optimization = 5,
        Learning = 6,
    }

    public enum UpdateID
    {
        Initialization = 0,
        Account = 1,
        Security = 2,
        Tick = 3,
        BarOpened = 4,
        BarClosed = 5,
        AskAboveTarget = 6,
        AskBelowTarget = 7,
        BidAboveTarget = 8,
        BidBelowTarget = 9,
        OpenedBuyStopOrder = 10,
        OpenedSellStopOrder = 11,
        ModifiedBuyStopOrderVolume = 12,
        ModifiedSellStopOrderVolume = 13,
        ModifiedBuyStopOrderStopPrice = 14,
        ModifiedSellStopOrderStopPrice = 15,
        ModifiedBuyStopOrderStopLoss = 16,
        ModifiedSellStopOrderStopLoss = 17,
        ModifiedBuyStopOrderTakeProfit = 18,
        ModifiedSellStopOrderTakeProfit = 19,
        ClosedBuyStopOrder = 20,
        ClosedSellStopOrder = 21,
        FilledBuyStopOrder = 22,
        FilledSellStopOrder = 23,
        ExpiredBuyStopOrder = 24,
        ExpiredSellStopOrder = 25,
        OpenedBuyLimitOrder = 26,
        OpenedSellLimitOrder = 27,
        ModifiedBuyLimitOrderVolume = 28,
        ModifiedSellLimitOrderVolume = 29,
        ModifiedBuyLimitOrderLimitPrice = 30,
        ModifiedSellLimitOrderLimitPrice = 31,
        ModifiedBuyLimitOrderStopLoss = 32,
        ModifiedSellLimitOrderStopLoss = 33,
        ModifiedBuyLimitOrderTakeProfit = 34,
        ModifiedSellLimitOrderTakeProfit = 35,
        ClosedBuyLimitOrder = 36,
        ClosedSellLimitOrder = 37,
        FilledBuyLimitOrder = 38,
        FilledSellLimitOrder = 39,
        ExpiredBuyLimitOrder = 40,
        ExpiredSellLimitOrder = 41,
        OpenedBuyStopLimitOrder = 42,
        OpenedSellStopLimitOrder = 43,
        ModifiedBuyStopLimitOrderVolume = 44,
        ModifiedSellStopLimitOrderVolume = 45,
        ModifiedBuyStopLimitOrderStopPrice = 46,
        ModifiedSellStopLimitOrderStopPrice = 47,
        ModifiedBuyStopLimitOrderLimitPrice = 48,
        ModifiedSellStopLimitOrderLimitPrice = 49,
        ModifiedBuyStopLimitOrderStopLoss = 50,
        ModifiedSellStopLimitOrderStopLoss = 51,
        ModifiedBuyStopLimitOrderTakeProfit = 52,
        ModifiedSellStopLimitOrderTakeProfit = 53,
        ClosedBuyStopLimitOrder = 54,
        ClosedSellStopLimitOrder = 55,
        FilledBuyStopLimitOrder = 56,
        FilledSellStopLimitOrder = 57,
        ExpiredBuyStopLimitOrder = 58,
        ExpiredSellStopLimitOrder = 59,
        OpenedBuyPosition = 60,
        OpenedSellPosition = 61,
        ModifiedBuyPositionVolume = 62,
        ModifiedSellPositionVolume = 63,
        ModifiedBuyPositionStopLoss = 64,
        ModifiedSellPositionStopLoss = 65,
        ModifiedBuyPositionTakeProfit = 66,
        ModifiedSellPositionTakeProfit = 67,
        ClosedBuyPosition = 68,
        ClosedSellPosition = 69,
        StopLossBuyPosition = 70,
        StopLossSellPosition = 71,
        TakeProfitBuyPosition = 72,
        TakeProfitSellPosition = 73,
        MarginCallBuyPosition = 74,
        MarginCallSellPosition = 75,
        Complete = 76,
        Denied = 77,
        Exception = 78,
        Shutdown = 79,
    }

    public enum ActionID
    {
        Initialization = 0,
        AskAboveTarget = 1,
        AskBelowTarget = 2,
        BidAboveTarget = 3,
        BidBelowTarget = 4,
        OpenBuyStopOrder = 5,
        OpenSellStopOrder = 6,
        ModifyBuyStopOrderVolume = 7,
        ModifySellStopOrderVolume = 8,
        ModifyBuyStopOrderStopPrice = 9,
        ModifySellStopOrderStopPrice = 10,
        ModifyBuyStopOrderStopLoss = 11,
        ModifySellStopOrderStopLoss = 12,
        ModifyBuyStopOrderTakeProfit = 13,
        ModifySellStopOrderTakeProfit = 14,
        CloseBuyStopOrder = 15,
        CloseSellStopOrder = 16,
        OpenBuyLimitOrder = 17,
        OpenSellLimitOrder = 18,
        ModifyBuyLimitOrderVolume = 19,
        ModifySellLimitOrderVolume = 20,
        ModifyBuyLimitOrderLimitPrice = 21,
        ModifySellLimitOrderLimitPrice = 22,
        ModifyBuyLimitOrderStopLoss = 23,
        ModifySellLimitOrderStopLoss = 24,
        ModifyBuyLimitOrderTakeProfit = 25,
        ModifySellLimitOrderTakeProfit = 26,
        CloseBuyLimitOrder = 27,
        CloseSellLimitOrder = 28,
        OpenBuyStopLimitOrder = 29,
        OpenSellStopLimitOrder = 30,
        ModifyBuyStopLimitOrderVolume = 31,
        ModifySellStopLimitOrderVolume = 32,
        ModifyBuyStopLimitOrderStopPrice = 33,
        ModifySellStopLimitOrderStopPrice = 34,
        ModifyBuyStopLimitOrderLimitPrice = 35,
        ModifySellStopLimitOrderLimitPrice = 36,
        ModifyBuyStopLimitOrderStopLoss = 37,
        ModifySellStopLimitOrderStopLoss = 38,
        ModifyBuyStopLimitOrderTakeProfit = 39,
        ModifySellStopLimitOrderTakeProfit = 40,
        CloseBuyStopLimitOrder = 41,
        CloseSellStopLimitOrder = 42,
        OpenBuyPosition = 43,
        OpenSellPosition = 44,
        ModifyBuyPositionVolume = 45,
        ModifySellPositionVolume = 46,
        ModifyBuyPositionStopLoss = 47,
        ModifySellPositionStopLoss = 48,
        ModifyBuyPositionTakeProfit = 49,
        ModifySellPositionTakeProfit = 50,
        CloseBuyPosition = 51,
        CloseSellPosition = 52,
        Complete = 53,
    }
}