namespace Connector
{
    public enum PositionTypeID
    {
        Normal = 0,
        Continuation = 1,
    }

    public enum StrategyType
    {
        Download = 1,
        NNFX = 2,
        DDPG = 3,
    }

    public enum VerboseLevel
    {
        Silent = 0,
        Exception = 1,
        Error = 2,
        Warning = 3,
        Alert = 4,
        Info = 5,
        Debug = 6,
    }

    public enum SystemMode
    {
        Live = 1,
        Simulation = 2,
        Testing = 3,
        Backtesting = 4,
        Optimization = 5,
        Learning = 6,
    }

    public enum UpdateID
    {
        Init = 0,
        Account = 1,
        Security = 2,
        Execution = 3,
        Tick = 4,
        BarOpened = 5,
        BarClosed = 6,
        AskAboveTarget = 7,
        AskBelowTarget = 8,
        BidAboveTarget = 9,
        BidBelowTarget = 10,
        OpenedBuyStopOrder = 11,
        OpenedSellStopOrder = 12,
        ModifiedBuyStopOrderVolume = 13,
        ModifiedSellStopOrderVolume = 14,
        ModifiedBuyStopOrderStopPrice = 15,
        ModifiedSellStopOrderStopPrice = 16,
        ModifiedBuyStopOrderStopLoss = 17,
        ModifiedSellStopOrderStopLoss = 18,
        ModifiedBuyStopOrderTakeProfit = 19,
        ModifiedSellStopOrderTakeProfit = 20,
        ClosedBuyStopOrder = 21,
        ClosedSellStopOrder = 22,
        FilledBuyStopOrder = 23,
        FilledSellStopOrder = 24,
        ExpiredBuyStopOrder = 25,
        ExpiredSellStopOrder = 26,
        OpenedBuyLimitOrder = 27,
        OpenedSellLimitOrder = 28,
        ModifiedBuyLimitOrderVolume = 29,
        ModifiedSellLimitOrderVolume = 30,
        ModifiedBuyLimitOrderLimitPrice = 31,
        ModifiedSellLimitOrderLimitPrice = 32,
        ModifiedBuyLimitOrderStopLoss = 33,
        ModifiedSellLimitOrderStopLoss = 34,
        ModifiedBuyLimitOrderTakeProfit = 35,
        ModifiedSellLimitOrderTakeProfit = 36,
        ClosedBuyLimitOrder = 37,
        ClosedSellLimitOrder = 38,
        FilledBuyLimitOrder = 39,
        FilledSellLimitOrder = 40,
        ExpiredBuyLimitOrder = 41,
        ExpiredSellLimitOrder = 42,
        OpenedBuyStopLimitOrder = 43,
        OpenedSellStopLimitOrder = 44,
        ModifiedBuyStopLimitOrderVolume = 45,
        ModifiedSellStopLimitOrderVolume = 46,
        ModifiedBuyStopLimitOrderStopPrice = 47,
        ModifiedSellStopLimitOrderStopPrice = 48,
        ModifiedBuyStopLimitOrderLimitPrice = 49,
        ModifiedSellStopLimitOrderLimitPrice = 50,
        ModifiedBuyStopLimitOrderStopLoss = 51,
        ModifiedSellStopLimitOrderStopLoss = 52,
        ModifiedBuyStopLimitOrderTakeProfit = 53,
        ModifiedSellStopLimitOrderTakeProfit = 54,
        ClosedBuyStopLimitOrder = 55,
        ClosedSellStopLimitOrder = 56,
        FilledBuyStopLimitOrder = 57,
        FilledSellStopLimitOrder = 58,
        ExpiredBuyStopLimitOrder = 59,
        ExpiredSellStopLimitOrder = 60,
        OpenedBuyPosition = 61,
        OpenedSellPosition = 62,
        ModifiedBuyPositionVolume = 63,
        ModifiedSellPositionVolume = 64,
        ModifiedBuyPositionStopLoss = 65,
        ModifiedSellPositionStopLoss = 66,
        ModifiedBuyPositionTakeProfit = 67,
        ModifiedSellPositionTakeProfit = 68,
        ClosedBuyPosition = 69,
        ClosedSellPosition = 70,
        StopLossBuyPosition = 71,
        StopLossSellPosition = 72,
        TakeProfitBuyPosition = 73,
        TakeProfitSellPosition = 74,
        MarginCallBuyPosition = 75,
        MarginCallSellPosition = 76,
        Complete = 77,
        Denied = 78,
        Exception = 79,
        Shutdown = 80,
    }

    public enum ActionID
    {
        Init = 0,
        Execution = 1,
        AskAboveTarget = 2,
        AskBelowTarget = 3,
        BidAboveTarget = 4,
        BidBelowTarget = 5,
        OpenBuyStopOrder = 6,
        OpenSellStopOrder = 7,
        ModifyBuyStopOrderVolume = 8,
        ModifySellStopOrderVolume = 9,
        ModifyBuyStopOrderStopPrice = 10,
        ModifySellStopOrderStopPrice = 11,
        ModifyBuyStopOrderStopLoss = 12,
        ModifySellStopOrderStopLoss = 13,
        ModifyBuyStopOrderTakeProfit = 14,
        ModifySellStopOrderTakeProfit = 15,
        CloseBuyStopOrder = 16,
        CloseSellStopOrder = 17,
        OpenBuyLimitOrder = 18,
        OpenSellLimitOrder = 19,
        ModifyBuyLimitOrderVolume = 20,
        ModifySellLimitOrderVolume = 21,
        ModifyBuyLimitOrderLimitPrice = 22,
        ModifySellLimitOrderLimitPrice = 23,
        ModifyBuyLimitOrderStopLoss = 24,
        ModifySellLimitOrderStopLoss = 25,
        ModifyBuyLimitOrderTakeProfit = 26,
        ModifySellLimitOrderTakeProfit = 27,
        CloseBuyLimitOrder = 28,
        CloseSellLimitOrder = 29,
        OpenBuyStopLimitOrder = 30,
        OpenSellStopLimitOrder = 31,
        ModifyBuyStopLimitOrderVolume = 32,
        ModifySellStopLimitOrderVolume = 33,
        ModifyBuyStopLimitOrderStopPrice = 34,
        ModifySellStopLimitOrderStopPrice = 35,
        ModifyBuyStopLimitOrderLimitPrice = 36,
        ModifySellStopLimitOrderLimitPrice = 37,
        ModifyBuyStopLimitOrderStopLoss = 38,
        ModifySellStopLimitOrderStopLoss = 39,
        ModifyBuyStopLimitOrderTakeProfit = 40,
        ModifySellStopLimitOrderTakeProfit = 41,
        CloseBuyStopLimitOrder = 42,
        CloseSellStopLimitOrder = 43,
        OpenBuyPosition = 44,
        OpenSellPosition = 45,
        ModifyBuyPositionVolume = 46,
        ModifySellPositionVolume = 47,
        ModifyBuyPositionStopLoss = 48,
        ModifySellPositionStopLoss = 49,
        ModifyBuyPositionTakeProfit = 50,
        ModifySellPositionTakeProfit = 51,
        CloseBuyPosition = 52,
        CloseSellPosition = 53,
        Complete = 54,
    }
}