import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from Library.Logging import LoggingAPI
from Library.Utility.Path import traceback_root
from Script.Task import attempt

OUTPUT_PATH = traceback_root() / "Sources" / "Robots" / "Connector" / "Connector" / "Enum.cs"

GENERATED_HEADER = "// <auto-generated>\n// Generated by Script/Setup/Enum.py from the Python enumerations - run python -m Script.Setup.Enum after any enum edit\n// </auto-generated>"

def enum_block(name: str, enumeration, flags: bool = False) -> str:
    body = "\n".join(f"    {member.name} = {member.value}," for member in enumeration)
    attribute = "[System.Flags]\n" if flags else ""
    return f"{attribute}public enum {name}\n{{\n{body}\n}}"

def write_enum_file(blocks: list[str]) -> Path:
    body = "\n\n".join(blocks)
    content = f"{GENERATED_HEADER}\n\nnamespace Connector;\n\n{body}"
    OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    return OUTPUT_PATH

def write_all() -> Path:
    from Script.Setup.Position import position_block
    from Script.Setup.Strategy import strategy_block
    from Script.Setup.Logging import logging_block
    from Script.Setup.System import system_block
    from Script.Setup.Update import update_block
    from Script.Setup.Action import action_block
    from Script.Setup.Stream import stream_block
    return write_enum_file([position_block(), strategy_block(), logging_block(), system_block(), update_block(), action_block(), stream_block()])

def main(database="Quant"):
    with LoggingAPI() as log:
        return attempt(log, "Enums", lambda: write_all().name)

if __name__ == "__main__":
    raise SystemExit(main())